function [head_ind,notail_ind] = hip_PCAind(dirVect,headPoint,tailPoint,X,x,y,z)
%hip_PCAind Method to obtain the indexes of the tail and heads
%   Calculates volumes of the hippocampus segments based on the given variables.
%   
%   01/2017: GLU: First version
%
% (C) Garikoitz Lerma-Usabiaga
% BCBL. Basque Center on Cognition, Brain and Language. 
% Stanford University
% 2017
% Contact: garikoitz@gmail.com


head_ind = (X(:,z)  - ...
                       ((dirVect(x)*(headPoint(x)-X(:,1)) + ... 
                         dirVect(y)*(headPoint(y)-X(:,2)))/dirVect(z) + ...
                        headPoint(z))   ...
            ) > 0;

 notail_ind = (X(:,z) - ...
                ((dirVect(x)*(tailPoint(x)-X(:,x)) + ...
                  dirVect(y)*(tailPoint(y)-X(:,y)))/dirVect(z) + ...
                 tailPoint(z)) ...   
              ) > 0;
end